<?php

declare(strict_types=1);

namespace Agtp;

use Closure;
use ReflectionFunction;
use RuntimeException;

/**
 * Generates daemon-side endpoint TOML files from registered handlers.
 *
 * Closes the silent-drift gap: today the agtpd endpoint TOMLs in
 * /etc/agtpd/endpoints/ and the `#[AgtpEndpoint]` attributes on PHP
 * handler classes are maintained independently. A mismatch is only
 * surfaced at runtime as `handler_not_found` in the register frame.
 *
 * The exporter walks ``HandlerRegistry::all()`` and emits one TOML
 * file per registered handler, projecting the attribute values into
 * the daemon's expected schema. The handler reference is derived via
 * Reflection on the bound closure: for class-method handlers we emit
 * ``FQCN::method``; for global-function handlers we emit the bare
 * function name; for anonymous closures we emit a comment marker
 * (closures can't be referenced statically — they're typically only
 * used in test setups, not production manifests).
 *
 * The SDK has no TOML library dependency. The TOML we emit is a
 * deliberately constrained subset: sections, scalar strings, scalar
 * integers, and string arrays. Hand-rolling keeps the SDK
 * dependency-free.
 *
 * Typical use is through ``drush agtp:export-manifest`` (Drupal) or
 * ``bin/console agtp:export-manifest`` (Symfony). Both connectors call
 * into this class.
 */
final class ManifestExporter
{
    public function __construct(
        private readonly HandlerRegistry $registry,
    ) {
    }

    /**
     * Write one TOML file per handler into $outputDir.
     *
     * Returns the list of absolute paths written. The directory is
     * created if it does not exist. Existing files with the same
     * generated name are overwritten — the attribute is the source
     * of truth.
     *
     * @return list<string>
     */
    public function writeToDirectory(string $outputDir): array
    {
        if (!is_dir($outputDir) && !@mkdir($outputDir, 0o755, true) && !is_dir($outputDir)) {
            throw new RuntimeException("could not create output directory: {$outputDir}");
        }

        $written = [];
        foreach ($this->registry->all() as $entry) {
            $filename = $this->filenameFor($entry);
            $contents = $this->render($entry);
            $path = rtrim($outputDir, '/\\') . DIRECTORY_SEPARATOR . $filename;
            if (file_put_contents($path, $contents) === false) {
                throw new RuntimeException("could not write {$path}");
            }
            $written[] = $path;
        }
        return $written;
    }

    /**
     * Render every registered handler as a single concatenated TOML
     * string, with file headers between sections. Useful for review
     * before writing, or for emitting a single manifest blob.
     */
    public function renderAll(): string
    {
        $parts = [];
        foreach ($this->registry->all() as $entry) {
            $parts[] = "# " . $this->filenameFor($entry) . "\n" . $this->render($entry);
        }
        return implode("\n\n", $parts);
    }

    /**
     * Render a single handler as a TOML document.
     */
    public function render(RegisteredHandler $entry): string
    {
        $kind = $this->resolveHandlerKind($entry);

        $lines = [];
        $lines[] = "# Generated by Agtp\\ManifestExporter. Do not edit by hand;";
        $lines[] = "# the #[AgtpEndpoint] attribute on the PHP handler is the";
        $lines[] = "# source of truth. Regenerate after attribute changes.";
        $lines[] = '';
        $lines[] = '[endpoint]';
        $lines[] = $this->kv('method', $entry->method);
        $lines[] = $this->kv('path', $entry->path);
        if ($entry->description !== '') {
            $lines[] = $this->kv('description', $entry->description);
        }
        if (!empty($entry->errors)) {
            $lines[] = 'errors = ' . $this->arrayOfStrings($entry->errors);
        }
        if (!empty($entry->requiredScopes)) {
            $lines[] = 'required_scopes = ' . $this->arrayOfStrings($entry->requiredScopes);
        }
        $lines[] = '';
        $lines[] = '[endpoint.handler]';
        $lines[] = $this->kv('type', 'registered_function');

        if ($kind['kind'] === 'class_method') {
            $lines[] = $this->kv('function', $kind['reference']);
        } elseif ($kind['kind'] === 'global_function') {
            $lines[] = $this->kv('function', $kind['reference']);
        } else {
            // Closure: cannot generate a static reference. Emit a
            // marker so the operator sees this explicitly.
            $lines[] = '# warning: handler is an anonymous closure;';
            $lines[] = '# cannot emit a stable function reference.';
            $lines[] = $this->kv('function', '__closure__');
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Generate a stable, filesystem-safe filename for the entry.
     *
     * Convention: `<method-lower>_<path-slug>.toml`. Slashes become
     * underscores; non-alphanumerics become hyphens; collapses
     * repeated separators.
     */
    public function filenameFor(RegisteredHandler $entry): string
    {
        $method = strtolower($entry->method);
        $path = trim($entry->path, '/');
        if ($path === '') {
            $slug = 'root';
        } else {
            $slug = preg_replace('/[^a-zA-Z0-9]+/', '-', $path) ?? $path;
            $slug = trim((string) $slug, '-');
        }
        return "{$method}_{$slug}.toml";
    }

    /**
     * @return array{kind: string, reference: string}
     */
    private function resolveHandlerKind(RegisteredHandler $entry): array
    {
        $handler = $entry->handler;
        if (!$handler instanceof Closure) {
            // The handler was registered as a non-closure callable
            // (string, [obj, 'method'], etc.). Best-effort stringify.
            if (is_string($handler)) {
                return ['kind' => 'global_function', 'reference' => $handler];
            }
            if (is_array($handler) && count($handler) === 2) {
                [$target, $method] = $handler;
                $class = is_object($target) ? $target::class : (string) $target;
                return ['kind' => 'class_method', 'reference' => $class . '::' . (string) $method];
            }
            return ['kind' => 'closure', 'reference' => '__closure__'];
        }

        $rf = new ReflectionFunction($handler);
        $name = $rf->getName();

        if ($name === '{closure}' || str_ends_with($name, '{closure}')) {
            // Could still be a method-bound closure produced by
            // ReflectionMethod::getClosure(). Check the scope.
            $scope = $rf->getClosureScopeClass();
            $shortName = $rf->getShortName();
            if ($scope !== null && $shortName !== '' && $shortName !== '{closure}') {
                return [
                    'kind' => 'class_method',
                    'reference' => $scope->getName() . '::' . $shortName,
                ];
            }
            return ['kind' => 'closure', 'reference' => '__closure__'];
        }

        // Non-{closure} name → either a global function exposed via
        // getClosure(), or a class method whose closure name is the
        // method name. Distinguish by checking the closure scope.
        $scope = $rf->getClosureScopeClass();
        if ($scope !== null) {
            return [
                'kind' => 'class_method',
                'reference' => $scope->getName() . '::' . $name,
            ];
        }
        return ['kind' => 'global_function', 'reference' => $name];
    }

    private function kv(string $key, string $value): string
    {
        return $key . ' = ' . $this->str($value);
    }

    private function str(string $value): string
    {
        // TOML basic string: double-quoted, with \ and " escaped, plus
        // control characters as \uXXXX. We stay conservative and
        // escape control bytes individually.
        $escaped = '';
        $length = strlen($value);
        for ($i = 0; $i < $length; $i++) {
            $byte = $value[$i];
            $ord = ord($byte);
            $escaped .= match (true) {
                $byte === '\\' => '\\\\',
                $byte === '"'  => '\"',
                $byte === "\n" => '\n',
                $byte === "\r" => '\r',
                $byte === "\t" => '\t',
                $ord < 0x20    => sprintf('\u%04X', $ord),
                default        => $byte,
            };
        }
        return '"' . $escaped . '"';
    }

    /**
     * @param list<string> $values
     */
    private function arrayOfStrings(array $values): string
    {
        $parts = array_map(fn(string $v) => $this->str($v), $values);
        return '[' . implode(', ', $parts) . ']';
    }
}
